/**
 * A workout that is happening right now.
 *
 * WHAT THIS REPLACES. Logging was a form you filled in after the gym: the whole
 * session lived in the open browser tab and one button at the end wrote it
 * down. A dead phone, a dropped tab or a mistaken back-swipe lost every set,
 * and nothing on any screen had been saved. This makes a workout a row from the
 * moment it starts, and every set a write as you tick it off.
 *
 * SEPARATE FROM `healthRepo`, which owns reading and writing workouts that are
 * already over (and is 775 lines). The split is by tense, not by table: this
 * file is the only thing that writes a workout with no end on it.
 *
 * WHY THE ENGINE IS CALLED HERE. It is pure and takes the program plus the
 * enrollment, both of which this file has. Finishing therefore computes the new
 * weights in TypeScript and hands them to `finish_program_workout`, which
 * applies them and closes the workout in one transaction — because the two used
 * to be separate writes, and a failure between them left the weights advanced
 * with no workout to replay from.
 */

import { createServerSupabaseClient } from "./supabase"
import { getEnrollmentById, programFor, plateSetupFor } from "./programRepo"
import { getUserTimezone } from "./settingsRepo"
import { toDateISO, toZonedDate } from "@/src/shared/dateUtils"
import { detectPersonalRecords } from "@/src/health/healthService"
import {
  applyLog,
  computePrescription,
  entriesFromSets,
  loadStyleOf,
  toKg,
  fromKg,
} from "@/src/programs/programsService"
import { scheduleDays } from "@/src/programs/customize"
import type {
  LiveWorkout,
  LiveWorkoutSet,
  ProgressionChange,
  StoredSet,
  UnitSystem,
  WorkoutAdjustments,
  WorkoutSummary,
} from "@/src/programs/types"
import type { PersonalRecord, WorkoutSetRow } from "@/src/health/types"

const round2 = (n: number) => Math.round(n * 100) / 100

/** Every column a live workout screen needs, plus its sets. */
const LIVE_SELECT = "*, workout_sets(*)"

interface LiveRow {
  id: string
  user_id: string
  session_type: string
  started_at: string | null
  ended_at: string | null
  enrollment_id: string | null
  program_day_id: string | null
  program_cycle: number | null
  program_week: number | null
  adjustments: WorkoutAdjustments | null
  notes: string | null
  rpe: number | null
  client_key: string | null
  logged_at: string
  workout_sets: WorkoutSetRow[] | null
}

/**
 * A stored workout as the live screen needs it.
 *
 * `unit` is passed in rather than assumed, because the screen renders and
 * re-submits these numbers: handing it kilograms under a "lb" label is how a
 * 135 lb bench became a 61 lb one on the second tap.
 */
function toLive(row: LiveRow, unit: UnitSystem): LiveWorkout {
  return {
    id: row.id,
    startedAt: row.started_at!,
    enrollmentId: row.enrollment_id,
    dayId: row.program_day_id,
    cycle: row.program_cycle,
    week: row.program_week,
    adjustments: row.adjustments ?? {},
    notes: row.notes,
    rpe: row.rpe,
    unit,
    sets: (row.workout_sets ?? [])
      .map(
        (s): LiveWorkoutSet => ({
          id: s.id,
          exerciseId: s.exercise_id,
          exercise: s.exercise,
          weight: round2(fromKg(s.weight_kg, unit)),
          weightKg: s.weight_kg,
          reps: s.reps,
          setNumber: s.set_number,
          kind: s.set_kind,
          prescribedIndex: s.prescribed_index,
          completedAt: s.completed_at,
          rpe: s.rpe,
          side: s.side,
        })
      )
      .sort((a, b) => a.setNumber - b.setNumber),
  }
}

/**
 * Start a workout, or return the one this browser already started.
 *
 * `clientKey` is generated by the browser BEFORE the request goes out, so a
 * retry after a dropped connection returns the same workout instead of opening
 * a second one. Without it, a gym with bad signal produces a workout per tap.
 */
export async function startWorkout(
  userId: string,
  input: { enrollmentId?: string | null; dayId?: string | null; clientKey: string }
): Promise<LiveWorkout> {
  const supabase = await createServerSupabaseClient()

  const existing = await getLiveWorkout(userId)
  if (existing) {
    // The same start, retried: hand back what it already made.
    const { data } = await supabase
      .from("workout_logs")
      .select("client_key")
      .eq("id", existing.id)
      .single()
    if (data?.client_key === input.clientKey) return existing
    throw new Error(
      "A workout is already in progress. Finish or discard it before starting another."
    )
  }

  let program: Awaited<ReturnType<typeof programFor>> | null = null
  let cycle: number | null = null
  let week: number | null = null
  let dayId: string | null = null

  if (input.enrollmentId) {
    const enr = await getEnrollmentById(userId, input.enrollmentId)
    if (!enr) throw new Error("That program was not found")
    program = programFor(enr)
    const prescription = computePrescription(program, enr)
    // The day the person picked, or the one the program offers next.
    dayId = input.dayId ?? prescription.dayId
    cycle = prescription.cycle
    week = prescription.week
  }

  const startedAt = new Date().toISOString()
  const { data, error } = await supabase
    .from("workout_logs")
    .insert({
      user_id: userId,
      session_type: "weights",
      // A workout belongs to the day it STARTED — a session that runs past
      // midnight is still the day you went to the gym.
      logged_at: startedAt,
      started_at: startedAt,
      ...(input.enrollmentId
        ? {
            enrollment_id: input.enrollmentId,
            program_day_id: dayId,
            program_cycle: cycle,
            program_week: week,
          }
        : {}),
      client_key: input.clientKey,
    })
    .select(LIVE_SELECT)
    .single()
  if (error) throw new Error(`Could not start the workout: ${error.message}`)
  return toLive(data as LiveRow, await unitFor(userId, input.enrollmentId ?? null))
}

/** The workout in progress, or null. At most one per person, by index. */
export async function getLiveWorkout(userId: string): Promise<LiveWorkout | null> {
  const supabase = await createServerSupabaseClient()
  const { data, error } = await supabase
    .from("workout_logs")
    .select(LIVE_SELECT)
    .eq("user_id", userId)
    .is("ended_at", null)
    .not("started_at", "is", null)
    .maybeSingle()
  if (error) throw new Error(`Could not read the workout: ${error.message}`)
  if (!data) return null
  const row = data as LiveRow
  return toLive(row, await unitFor(userId, row.enrollment_id))
}

/** The workout must be this person's, and must still be running. */
async function requireLive(userId: string, workoutId: string): Promise<LiveWorkout> {
  const live = await getLiveWorkout(userId)
  if (!live || live.id !== workoutId) {
    throw new Error("That workout is not open any more — reload to see where it got to.")
  }
  return live
}

/**
 * Tick a set off. THE WRITE THAT MAKES THIS A TRACKER RATHER THAN A FORM.
 *
 * Upserted on its slot, so tapping the same set twice corrects it rather than
 * adding a second one — which is what a retry over bad signal looks like.
 */
export async function completeSet(
  userId: string,
  workoutId: string,
  set: {
    exerciseId: string | null
    exercise: string
    weight: number
    reps: number
    setNumber: number
    kind?: "warmup" | "working" | "amrap" | "backoff" | "drop"
    prescribedIndex?: number | null
    side?: "left" | "right" | null
    rpe?: number | null
  }
): Promise<LiveWorkout> {
  const live = await requireLive(userId, workoutId)
  const unit = await unitFor(userId, live.enrollmentId)
  const supabase = await createServerSupabaseClient()

  const kind = set.kind ?? "working"
  const side = set.side ?? null
  const row = {
    exercise: set.exercise,
    exercise_id: set.exerciseId,
    weight_kg: round2(toKg(set.weight, unit)),
    reps: set.reps,
    set_number: set.setNumber,
    set_kind: kind,
    prescribed_index: set.prescribedIndex ?? null,
    completed_at: new Date().toISOString(),
    side,
    rpe: set.rpe ?? null,
  }

  /**
   * CORRECT THE SLOT, DO NOT ADD TO IT.
   *
   * Tapping the same set again is how a person fixes a number, and it is also
   * what a retry over bad signal looks like — neither should produce a second
   * set 2. Matched against the workout already in hand rather than through a
   * database upsert, because the uniqueness rule is an EXPRESSION index
   * (`COALESCE(exercise_id, exercise)`, so a loose workout with no lift ids
   * still cannot write one slot twice) and PostgREST's `onConflict` can only
   * name plain columns.
   */
  const slot = (s: { exerciseId: string | null; exercise: string; kind: string; setNumber: number; side: string | null }) =>
    `${s.exerciseId ?? s.exercise}|${s.kind}|${s.setNumber}|${s.side ?? ""}`
  const key = slot({ exerciseId: set.exerciseId, exercise: set.exercise, kind, setNumber: set.setNumber, side })
  const existing = live.sets.find((s) => slot(s) === key)

  const { error } = existing
    ? await supabase.from("workout_sets").update(row).eq("id", existing.id).eq("log_id", workoutId)
    : await supabase.from("workout_sets").insert({ ...row, log_id: workoutId })
  if (error) throw new Error(`Could not save that set: ${error.message}`)
  return (await getLiveWorkout(userId))!
}

/** Remove a set. Did three, not four. */
export async function deleteSet(
  userId: string,
  workoutId: string,
  setId: string
): Promise<LiveWorkout> {
  await requireLive(userId, workoutId)
  const supabase = await createServerSupabaseClient()
  const { error } = await supabase.from("workout_sets").delete().eq("id", setId).eq("log_id", workoutId)
  if (error) throw new Error(`Could not remove that set: ${error.message}`)
  return (await getLiveWorkout(userId))!
}

/**
 * What changed on the day: a lift skipped, swapped, cut short, reordered.
 *
 * On the workout rather than in its sets, because a lift you did NOT do has no
 * sets to carry the fact. Without it the engine cannot tell "the rack was
 * taken" from "I failed every rep", and it used to assume the second.
 */
export async function adjustWorkout(
  userId: string,
  workoutId: string,
  patch: Partial<WorkoutAdjustments> & { notes?: string | null; rpe?: number | null }
): Promise<LiveWorkout> {
  const live = await requireLive(userId, workoutId)
  const supabase = await createServerSupabaseClient()
  const { notes, rpe, ...adjustments } = patch
  const { error } = await supabase
    .from("workout_logs")
    .update({
      adjustments: { ...live.adjustments, ...adjustments },
      ...(notes !== undefined ? { notes } : {}),
      ...(rpe !== undefined ? { rpe } : {}),
    })
    .eq("id", workoutId)
    .eq("user_id", userId)
  if (error) throw new Error(`Could not save that change: ${error.message}`)
  return (await getLiveWorkout(userId))!
}

/**
 * Close the workout and move the program's weights — in one transaction.
 *
 * `endedAt` comes from the caller rather than from `now()`: a workout somebody
 * forgot to finish on Tuesday and closes on Thursday is not a two-day workout,
 * and the finish screen defaults it to the last set that was ticked.
 */
export async function finishWorkout(
  userId: string,
  workoutId: string,
  input: {
    endedAt?: string
    durationMin?: number
    intensity: number
    rpe?: number | null
    notes?: string | null
    sessionType?: "weights" | "cardio" | "mobility" | "yoga" | "running"
  }
): Promise<WorkoutSummary> {
  const live = await requireLive(userId, workoutId)
  const supabase = await createServerSupabaseClient()

  const lastSet = live.sets
    .map((s) => s.completedAt)
    .filter((t): t is string => Boolean(t))
    .sort()
    .pop()
  // Ended when the caller says, else when the last set was ticked, else now.
  const endedAtRaw = input.endedAt ?? lastSet ?? new Date().toISOString()
  const endedAt = endedAtRaw
  const started = new Date(live.startedAt).getTime()
  let ended = new Date(endedAt).getTime()
  /**
   * A MINUTE-PRECISION INPUT CANNOT EXPRESS SECONDS.
   *
   * The finish screen offers "when did it end" as a `datetime-local`, which has
   * no seconds — so a workout started at 20:43:37 and finished a moment later
   * comes back as 20:43:00, thirty-seven seconds BEFORE it began, and was
   * refused outright. Inside a minute the two are the same moment and the start
   * is the honest answer; beyond that it is a real mistake and still refused.
   */
  if (ended < started) {
    if (started - ended > 60_000) throw new Error("A workout cannot end before it started.")
    ended = started
  }
  const derivedMinutes = Math.max(1, Math.round((ended - started) / 60000))
  const durationMin = Math.min(599, Math.max(1, input.durationMin ?? derivedMinutes))

  // What the person actually beat. Read BEFORE the workout is closed, so its
  // own sets are not counted as their own previous best.
  const priorSets = await priorSetsFor(userId, workoutId)

  let changes: ProgressionChange[] = []
  let exerciseState: Record<string, unknown> | null = null
  let cursor: Record<string, unknown> | null = null
  let expectedSessionCount = 0

  if (live.enrollmentId) {
    const enr = await getEnrollmentById(userId, live.enrollmentId)
    if (!enr) throw new Error("That program was not found")
    const program = programFor(enr)
    const entries = entriesFromSets(live.sets.map(toStored), live.adjustments, enr.unitSystem)
    const result = applyLog(program, enr, {
      enrollment_id: enr.id,
      dayId: live.dayId ?? "",
      cycle: live.cycle ?? enr.cursor.cycle,
      week: live.week ?? enr.cursor.week,
      entries,
    })
    changes = result.changes
    exerciseState = result.enrollment.exerciseState as unknown as Record<string, unknown>
    cursor = result.enrollment.cursor as unknown as Record<string, unknown>
    expectedSessionCount = enr.cursor.sessionCount
  }

  const { error } = await supabase.rpc("finish_program_workout", {
    p_workout_id: workoutId,
    p_ended_at: endedAt,
    p_duration_min: durationMin,
    p_intensity: input.intensity,
    p_rpe: input.rpe ?? null,
    p_notes: input.notes ?? null,
    p_exercise_state: exerciseState,
    p_cursor: cursor,
    p_replay_events: null,
    p_expected_session_count: expectedSessionCount,
  })
  if (error) throw new Error(error.message)

  if (input.sessionType && input.sessionType !== "weights") {
    await supabase
      .from("workout_logs")
      .update({ session_type: input.sessionType })
      .eq("id", workoutId)
      .eq("user_id", userId)
  }

  const working = live.sets.filter((s) => s.kind !== "warmup" && s.kind !== "drop")
  const volumeKg = working.reduce((total, s) => total + s.weightKg * s.reps, 0)
  // The day the lifter trained, on the lifter's own calendar — not the server's.
  const workoutDay = toDateISO(toZonedDate(new Date(live.startedAt), await getUserTimezone(userId)))
  return {
    workoutId,
    durationMin,
    sets: working.length,
    // Timed work is measured in seconds, so multiplying it by a weight would
    // put a 40 kg carry's "1,200 kg" beside a squat's.
    volumeKg: round2(volumeKg),
    // The same number in the lifter's own unit. The summary used to print
    // "kg lifted" to somebody working entirely in pounds.
    volume: round2(fromKg(volumeKg, live.unit)),
    unit: live.unit,
    // A record cannot be claimed against a history that could not be read.
    recordsUnavailable: priorSets.unavailable,
    personalRecords: priorSets.unavailable
      ? []
      : newRecords(priorSets.sets, live.sets, workoutDay).map((pr) => ({
          ...pr,
          weight: round2(fromKg(pr.weight_kg, live.unit)),
        })),
    changes,
  }
}

/** Throw the workout away. Nothing is recorded. */
export async function discardWorkout(userId: string, workoutId: string): Promise<void> {
  await requireLive(userId, workoutId)
  const supabase = await createServerSupabaseClient()
  const { error } = await supabase.from("workout_logs").delete().eq("id", workoutId).eq("user_id", userId)
  if (error) throw new Error(`Could not discard the workout: ${error.message}`)
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function toStored(set: LiveWorkoutSet): StoredSet {
  return {
    exercise: set.exercise,
    exercise_id: set.exerciseId,
    weight_kg: set.weightKg,
    reps: set.reps,
    set_number: set.setNumber,
    set_kind: set.kind,
    side: set.side,
  }
}

/**
 * The unit this workout's weights are entered in.
 *
 * IT REFUSES RATHER THAN GUESSES. The error was discarded here, so a profile
 * read that failed came back as `null` and fell through to the "kg" default —
 * and a lifter working in pounds had their whole session silently reinterpreted
 * as kilograms. 225 becomes 225 kg going in and 496 lb coming out; the
 * progression engine then compares the two and stalls the weight. There is no
 * safe guess for this, so a failure stops the workout instead of corrupting it.
 */
async function unitFor(userId: string, enrollmentId: string | null): Promise<"kg" | "lb"> {
  if (enrollmentId) {
    const enr = await getEnrollmentById(userId, enrollmentId)
    if (enr) return enr.unitSystem
  }
  const supabase = await createServerSupabaseClient()
  const { data, error } = await supabase
    .from("profiles")
    .select("weight_unit")
    .eq("id", userId)
    .maybeSingle()
  if (error) {
    throw new Error("Could not read whether you train in kilos or pounds, so nothing was changed.")
  }
  return data?.weight_unit === "lb" ? "lb" : "kg"
}

/** Every set logged BEFORE this workout — the baseline a record is beaten from. */
/**
 * How many past workouts a personal best is measured against.
 *
 * BOUNDED, AND NEWEST FIRST. This read had no order and no limit, so once the
 * hosted row cap (PostgREST `db.max_rows`, 1000 by default) started biting, the
 * baseline became an arbitrary slice of somebody's history and the app would
 * announce "New best" for a lift they had beaten years earlier. Ordering makes
 * the window the RECENT past rather than a random one, and 400 workouts is
 * about three years of training twice a week.
 */
const PR_HISTORY_WORKOUTS = 400

/**
 * The history a record is measured against, or nothing if it could not be read.
 *
 * NO HISTORY IS NOT AN EMPTY HISTORY. The error was thrown away here, so a
 * failed read came back as zero past sets — and against a blank past, EVERY set
 * of the session is a personal best. A person finishing an ordinary Tuesday was
 * congratulated on six records at weights they had been lifting for months.
 *
 * The workout must still save: losing an hour of training because a
 * nice-to-have could not be computed is the worse trade. So the failure is
 * carried out with the answer, and the summary says it could not check rather
 * than claiming there was nothing to beat.
 */
async function priorSetsFor(
  userId: string,
  workoutId: string
): Promise<{ sets: (WorkoutSetRow & { logged_at: string })[]; unavailable: boolean }> {
  const supabase = await createServerSupabaseClient()
  const { data, error } = await supabase
    .from("workout_logs")
    .select("logged_at, workout_sets(*)")
    .eq("user_id", userId)
    .neq("id", workoutId)
    .not("ended_at", "is", null)
    .order("logged_at", { ascending: false })
    .limit(PR_HISTORY_WORKOUTS)
  if (error) {
    console.error("could not read training history for personal records:", error)
    return { sets: [], unavailable: true }
  }
  return {
    sets: ((data ?? []) as { logged_at: string; workout_sets: WorkoutSetRow[] | null }[]).flatMap((log) =>
      (log.workout_sets ?? []).map((s) => ({ ...s, logged_at: log.logged_at }))
    ),
    unavailable: false,
  }
}

/**
 * WHAT YOU BEAT. Personal records used to fire only for a workout logged
 * outside a program, so somebody following a program was never once told they
 * had set one — on the path the whole feature is built around.
 */
function newRecords(
  prior: (WorkoutSetRow & { logged_at: string })[],
  sets: LiveWorkoutSet[],
  onDate: string
): PersonalRecord[] {
  const asRows = sets.map(
    (s): WorkoutSetRow => ({
      id: s.id,
      log_id: "",
      exercise: s.exercise,
      weight_kg: s.weightKg,
      reps: s.reps,
      set_number: s.setNumber,
      notes: null,
      exercise_notes: null,
      exercise_id: s.exerciseId,
      library_id: null,
      set_kind: s.kind,
      prescribed_index: s.prescribedIndex,
      completed_at: s.completedAt,
      rpe: s.rpe,
      side: s.side,
    })
  )
  return detectPersonalRecords(prior, asRows, onDate)
}

/**
 * One lift's recent history — the sheet behind tapping its name.
 *
 * "What did I do for ALL of it last time" is the question a lifter actually
 * asks between sets, and the session screen could only answer "what did I do
 * for the set with this number".
 */
export async function liftHistory(
  userId: string,
  exerciseName: string,
  sessions = 3
): Promise<Array<{ at: string; sets: { weight: number; reps: number; kind: string }[] }>> {
  const supabase = await createServerSupabaseClient()
  const { data } = await supabase
    .from("workout_logs")
    .select("logged_at, workout_sets(exercise, weight_kg, reps, set_number, set_kind)")
    .eq("user_id", userId)
    .not("ended_at", "is", null)
    .order("logged_at", { ascending: false })
    .limit(40)

  const norm = exerciseName.trim().toLowerCase()
  const out: Array<{ at: string; sets: { weight: number; reps: number; kind: string }[] }> = []
  for (const log of (data ?? []) as {
    logged_at: string
    workout_sets: { exercise: string; weight_kg: number; reps: number; set_number: number; set_kind: string }[] | null
  }[]) {
    const mine = (log.workout_sets ?? [])
      .filter((s) => s.exercise.trim().toLowerCase() === norm)
      .sort((a, b) => a.set_number - b.set_number)
    if (mine.length === 0) continue
    out.push({
      at: log.logged_at,
      sets: mine.map((s) => ({ weight: s.weight_kg, reps: s.reps, kind: s.set_kind })),
    })
    if (out.length >= sessions) break
  }
  return out
}

/** Today's prescription, with the plate setup and the person's own weekday. */
export async function prescriptionForDay(userId: string, enrollmentId: string, dayId?: string) {
  const enr = await getEnrollmentById(userId, enrollmentId)
  if (!enr) throw new Error("That program was not found")
  const program = programFor(enr)
  const days = scheduleDays(program.schedule)
  const index = dayId ? days.findIndex((d) => d.id === dayId) : -1
  const prescription = computePrescription(
    program,
    index >= 0 ? { ...enr, cursor: { ...enr.cursor, dayIndex: index } } : enr
  )
  return {
    prescription,
    unit: enr.unitSystem,
    plates: plateSetupFor(enr.barWeightKg ?? null, enr.unitSystem),
    loadStyles: Object.fromEntries(
      days.flatMap((d) => d.exercises.map((ex) => [ex.id, loadStyleOf(ex)] as const))
    ),
    timezone: await getUserTimezone(userId),
  }
}
