#!/bin/bash
# scripts/check_youtube_cookies.sh
# Quick sanity checks for a YouTube cookies.txt export (Netscape format).
#
# Usage:
#   ./scripts/check_youtube_cookies.sh [cookies_file] [optional_test_url]
#
# Notes:
# - yt-dlp's --cookies reads AND writes the cookie jar back to that same path.
#   This script uses a temp copy for the optional yt-dlp probe so your export
#   is never overwritten.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

COOKIES_FILE="${1:-"$ROOT_DIR/www.youtube.com_cookies.txt"}"
TEST_URL="${2:-}"

if [[ ! -f "$COOKIES_FILE" ]]; then
  echo "❌ Missing cookies file: $COOKIES_FILE"
  echo "Put your exported cookies here (Netscape cookies.txt format):"
  echo "  $ROOT_DIR/www.youtube.com_cookies.txt"
  exit 1
fi

echo "Cookies file: $COOKIES_FILE"

if ! head -n 1 "$COOKIES_FILE" | grep -q "Netscape HTTP Cookie File"; then
  echo "⚠️  Unexpected format: first line is not 'Netscape HTTP Cookie File'"
fi

if grep -q "This file is generated by yt-dlp" "$COOKIES_FILE" 2>/dev/null; then
  echo "⚠️  This file looks like it was overwritten by yt-dlp."
  echo "   Re-export cookies from your browser profile while logged in."
fi

if grep -q $'\tLOGIN_INFO\t' "$COOKIES_FILE"; then
  echo "✅ LOGIN_INFO found (yt-dlp should treat these as authenticated cookies)"
else
  echo "⚠️  LOGIN_INFO not found (age-restricted/private videos will likely fail)"
fi

if grep -qE 'SAPISID|APISID|HSID|\tSID\t|__Secure-3PSID' "$COOKIES_FILE"; then
  echo "✅ Found one or more auth-related cookies (SAPISID/APISID/HSID/SID/__Secure-3PSID)"
else
  echo "⚠️  Missing common auth cookies (SAPISID/APISID/HSID/SID/__Secure-3PSID)"
fi

if [[ -n "$TEST_URL" ]]; then
  if ! command -v yt-dlp &> /dev/null; then
    echo "❌ yt-dlp not found; skipping network probe."
    exit 1
  fi

  echo ""
  echo "yt-dlp format probe (uses a temp copy, requires network):"
  tmp="$(mktemp)"
  cp "$COOKIES_FILE" "$tmp"
  yt-dlp --cookies "$tmp" -F "$TEST_URL"
  rm -f "$tmp"
fi

